### ISSUE TITLE
Timer Set Correctly? 

### ISSUE THREAD

**Issue by Jim-Rouse** [queueit/KnownUser.V3.JAVA#10]
https://github.com/queueit/KnownUser.V3.JAVA/blob/b3cf85f8c0fde69ad6dd27fe4244a68267ba3951/Documentation/IntegrationConfigProvider.java#L38

I believe the current implementation is wrong and needs to be this (first parameter is when to start 'the date', next is how often)
 , new Date(), REFRESH_INTERVALS_MS);

**Comment by Reza-0** [comment]
Hello @Jim-Rouse,

Thank you for reviewing our repository and for your comment. 
However, I have to disagree with this, as according to some references the current implementation is correct. [please see here](https://www.tutorialspoint.com/tutorial_view.htm?cid=java/util&pid=timer_schedule_period.htm)
