### ISSUE TITLE
Support for Spring Boot 3 by using Jarkata EE

### ISSUE THREAD

**Issue by cringland** [queueit/KnownUser.V3.JAVA#12]
Hi, I was wondering if there were any plans to switch from using Javax to Jakarta so that it is compatible or if there is another library somewhere that does this already

See this blog post for more details
https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0

Thanks

**Comment by Reza-0** [comment]
Hi,

Thank you for this post. 
We are looking into options to provide support for Jakarta.
Please be aware that some of our repositories are private on GitHub. To get access to the private repositories, you need to contact customer support at support@queue-it.com email.

Best regards,
Queue-it dev team

**Comment by JoannaZdunek** [comment]
We now support Jakarta with a new Java-based connector. Please reach out to our Customer Support at https://support.queue-it.com/hc/en-us) to receive access to the private repository and the documentation.
