### ISSUE TITLE
Using different keys for different events

### ISSUE THREAD

**Issue by aercolino** [queueit/KnownUser.V3.JAVA#2]
A `secretKey` is [currently passed](https://github.com/queueit/KnownUser.V3.JAVA/blob/7851c333dd2ff4814d54043a01d717e1a59caf82/SDK/src/main/java/queueit/knownuserv3/sdk/KnownUser.java#L41) to `KnownUser.validateRequestByIntegrationConfig` as a simple String. 

That's a problem because 

1. there is a _Secret Key_ field on each event, which makes it possible to use different keys for different events. 
1. However, `KnownUser.validateRequestByIntegrationConfig` is designed to work at once on all the published integrations, 
1. which means it decides on its own whether a `queueitToken` is valid o not, 
1. which means the `secretKey` it gets must work for all the events it manages, 
1. which makes it impossible to use different keys for different events.

If the type was instead a Map: eventId => secretKey, it would work great.

**Comment by sarooghi** [comment]
Hi @aercolino 
The secret key is supposed to be used per account (customer) not per event.
The secretkey field in the event tab is for legacy support will be removed soon (there will be just one secret key to be set in customer tab).
Please reach our support if you have a specific need to have multiple secret keys (different keys for different events).

**Comment by aercolino** [comment]
> The secretkey field in the event tab is for legacy support will be removed soon

Thanks for sharing it.

We assumed the opposite, that Queue-it's customers had had such a need in the past, and that's why the secret key field was in the event tab in the first place. In fact, years ago we developed our implementation of Known User V2 around that assumption, allowing different keys for different events.

**Comment by aercolino** [comment]
I just found out that using different keys for different events is the _expected_ configuration, not quite legacy yet. 

In the Queue-it /Account /Settings /Integration /KnownUser secret key section, I read:

> This is the default secret key...
> This default key can be overwritten by specifying new KnownUser secret keys on individual event settings.

![Screenshot 2020-08-13 at 09 46 07](https://user-images.githubusercontent.com/172373/90108351-76e10c00-dd4a-11ea-957e-95a453c3eed5.png)
