### ISSUE TITLE
SDK group and artifact ids don't use queueit name convention

### ISSUE THREAD

**Issue by diegodondiego** [queueit/KnownUser.V3.JAVA#5]
the 3.6.1 SDK version has this information for group and artifact:

 ```
  <groupId>x</groupId>
  <artifactId>y</artifactId>
  <version>1.0</version>
```

and when it's declared on pom.xml where it is used, the dependency becomes:

```
    <dependency>
      <groupId>x</groupId>
      <artifactId>y</artifactId>
      <version>1.0</version>
    </dependency>
```

which is not very helpful and maintainable. also the version is different.

can it be fixed it by using a queueit naming convention for packages and update the version, please?

**Comment by sp0x** [comment]
We've updated the groupId and artifactId.
The new details are:
 - groupId: com.queue-it.connector
 - artifactId: connector
 - version: 3.6.1
