### ISSUE TITLE
Provide the SDK library publicly

### ISSUE THREAD

**Issue by diegodondiego** [queueit/KnownUser.V3.JAVA#6]
Currently, to use the SDK we need to clone the repository and build the library ourselves. But this process make it complicated to maintain and be updated with any updates that is needed.

Please provide a final jar version of the SDK in a public repository (like maven public registry) or even on github.

**Comment by sp0x** [comment]
We've published the SDK to maven.
Refer to [installation section](https://github.com/queueit/KnownUser.V3.JAVA#installation) for more details.
