### ISSUE TITLE
Create secured cookie in CookieManager

### ISSUE THREAD

**Issue by guiliguili** [queueit/KnownUser.V3.JAVA#8]
QueueIT imposes to created secured cookie.

This should be enforced by the `Cookie` created by the `CookieManager`

**Comment by frwiqueueit** [comment]
Thank you. We will work towards have support for secure cookie in next release of this connector.

**Comment by frwiqueueit** [comment]
With release 3.7 secure cookies can now be set via integration configuration file setup in GO Queue-it platform.
