### ISSUE TITLE
Missing feild in IntegrationConfigModel

### ISSUE THREAD

**Issue by aamir0701** [queueit/KnownUser.V3.JAVA#9]
"IsCookieHttpOnly" field is missing causing error 

INFO   | jvm 1    | main    | 2021/09/11 11:49:30.283 | [m com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "IsCookieHttpOnly" (class queueit.sdk.integrationconfig.IntegrationConfigModel), not marked as ignorable (12 known properties: "ExtendCookieValidity", "RedirectLogic", "EventId", "CookieDomain", "CookieValidityMinute", "Name", "Culture", "ActionType", "LayoutName", "Triggers", "QueueDomain", "ForcedTargetUrl"])

**Comment by sp0x** [comment]
We're adding 3 new fields to the integration config JSON: IsCookieHttpOnly, IsCookieSecure and CookieSameSiteSetting(string)
You need to update your serialization code so it doesn't fail on new fields.
This code snippet might be useful:
```java
mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

We'll release an update to this SDK later on, so the fields are added to IntegrationConfigModel.

**Comment by frwiqueueit** [comment]
If the above is not a option for you, we have made sure that future publish from GO Queue-it Platform no longer includes the mentioned fields in resulting JSON config file.
